config/routes.rb
Rails.application.routes.draw do
  resources :github_repositories, only: [:index]
  root "github_repositories#index"
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/github_repositories_controller.rb
# frozen_string_literal: true

class GithubRepositoriesController < ApplicationController
  include Pagy::Backend

  def index
    @repositories = []
    fetch_repositories unless github_params[:name].blank?
  end

  private def fetch_repositories
    result = github_client.search_repositories(
      github_params[:name],
      page: github_params[:page],
      per_page: 5
    )
    @repositories = result.items
    @paginated_repositories, = pagy_array(
      @repositories,
      page: github_params[:page],
      count: result.total_count
    )
  end

  private def github_client
    @github_client ||= Octokit::Client.new
  end

  private def github_params
    params.permit(%i(name page))
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend

  def pagination(repositories)
    pagy_bootstrap_nav(@paginated_repositories) unless repositories.empty?
  end
end

app/helpers/github_repositories_helper.rb
# frozen_string_literal: true

module GithubRepositoriesHelper
  # include Pagy::Frontend
  #
  # def pagination(repositories)
  #   pagy_nav(@paginated_repositories) if repositories.size > 0
  # end
end

app/views/github_repositories/index.html.erb
<div class="row">
  <div class="col-sm-offset-3 ">
    <h2>Search Github repositories</h2>
    <%= form_tag(github_repositories_path, method: :get, class: "form-inline") do %>
      <%= text_field_tag :name, params[:name], required: true, class: "form-control input-lg" %>
      <%= submit_tag 'Search', name: nil, class: "btn btn-primary input-lg" %>
    <% end %>
    <% @repositories&.each do |repository| %>
      <h2> <%= link_to repository.full_name, repository.html_url %></h2>
      <p><%= repository.description %></p>
      <hr/>
    <% end %>
    <%== pagination(@repositories) %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adjust</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>